### ISSUE TITLE
Internal server error after uploading file

### ISSUE THREAD

**Issue by chrisaldrich** [martymcguire/screech#1]
I tried testing Screech in conjunction with WithKnown, uploaded a small 13 min test file, it properly scraped the metadata, and when I posted it appeared to upload the entire file, but then redirected to 
https://screech.schmarty.net/api/publish
which showed: "Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."
The post didn't make it to my site, so I'm not sure where things ran off the rails after upload, but before posting. (Maybe even simple server overload as I'm testing this minutes after you unleashed it?)

Kudos, btw!

**Comment by martymcguire** [comment]
Thanks for the report! I had a bug in the code that checks HTTP return codes that was being triggered by Known rejecting the post. That bug was fixed in 261986ec, but uploads were still failing on a fresh Known instance that I set up.

I checked the logs and found this error:

    PHP Warning:  POST Content-Length of 10833766 bytes exceeds the limit of 8388608 bytes in Unknown on line 0

So it looks the default configuration of the box I set up (Apache2 + PHP7 on Ubuntu 16.04) has a post size limit of ~8MB. I was able to raise that number on my fresh install by editing `/etc/php/7.0/apache2/php.ini
` and raising the value of `post_max_size` to something larger than the file I was trying to upload. I picked `200M`.

After restarting Apache I was able to submit the post.

From there I discovered a larger issue with posting from Screech to Known. It looks like the IndiePub plugin for Known, which provides micropub support, doesn't support `audio` posts!

* [The current 0.9.2 release of Known supports photo, but not video or audio](https://github.com/idno/Known/blob/v0.9.2/IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php#L89)
* [The current master branch supports photo and video, but not audio](https://github.com/idno/Known/blob/v0.9.2/IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php#L89)

I'm going to close this issue for now and make a new issue on the Known repo, if one doesn't already exist.

Feel free to re-open this, or start a new issue, if you run into more problems!

**Comment by martymcguire** [comment]
Issue submitted: https://github.com/idno/Known/issues/1664

**Comment by martymcguire** [comment]
Note: I also had to change `upload_max_filesize` to something larger than the default of `2M` before audio posts would work, even from Known's interface.

**Comment by martymcguire** [comment]
PR submitted: https://github.com/idno/Known/pull/1665
